### ISSUE TITLE
Dodać obslugę komunikatu io.github.wulkanowy.utils.security.ScramblerException

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1701]
Dodać obsługę komunikatu:
`io.github.wulkanowy.utils.security.ScramblerException: An error occurred while decrypting text
at io.github.wulkanowy.utils.security.ScramblerKt.decrypt(Scrambler.kt:113)
at io.github.wulkanowy.data.repositories.StudentRepository$getCurrentStudent$2.invokeSuspend(StudentRepository.kt:92)
...
at java.security.KeyStore.getKey(KeyStore.java:825)
at io.github.wulkanowy.utils.security.ScramblerKt.isKeyPairExists(Scrambler.kt:45)
at io.github.wulkanowy.utils.security.ScramblerKt.decrypt(Scrambler.kt:90)
... 7 more
Caused by: android.security.KeyStoreException: OK
at android.security.KeyStore.getKeyStoreException(KeyStore.java:645)
at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
... 13 more`

**Comment by Faierbel** [comment]
Aktualny dialog z Wygasłą sesją jest wystarczający. Planujemy takżę pozbyć w całości tego błędu
