### ISSUE TITLE
Wulkanowy rzuca błędami na lewo i prawo tak jakby chciał wszystko robić przed złapaniem autoryzacji z dziennika 

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#2279]
## Co się dzieje
Wulkanowy wyświetla dziwne komunikaty "Nieznany błąd aplikacji" z tytułem w środku że "Trwa wylogowywanie..." (Raz na wejście w dowolną zakładkę a czasami wcale):
![image](https://github.com/wulkanowy/wulkanowy/assets/43276401/2b501245-3a15-4f9e-9274-dd74b34b0126)
```
io.github.wulkanowy.sdk.scrapper.exception.ScrapperException: Trwa wylogowanie...
    at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorInterceptor.checkForError(ErrorInterceptor.kt:98)
    at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorInterceptor.intercept(ErrorInterceptor.kt:35)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
 ```
I czasami po wejściu do aplikacji na daskboard rzuca komunikatem:
```
io.github.wulkanowy.sdk.scrapper.login.NotLoggedInException: The custom error module does not recognize this error.
    at io.github.wulkanowy.sdk.scrapper.interceptor.HttpErrorInterceptor.intercept(HttpErrorInterceptor.kt:18)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at io.github.wulkanowy.sdk.scrapper.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:35)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at io.github.wulkanowy.sdk.scrapper.interceptor.AutoLoginInterceptor.intercept(AutoLoginInterceptor.kt:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorInterceptor.intercept(ErrorInterceptor.kt:31)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```
Albo dostaje komunikat o braku uprawnień tak jakby apka chciała robić wszystko przed autoryzacją w dzienniku.
## Jak to zrobić kolejny raz:
Nie da się tego powtórzyć to często się dzieje podczas uruchomienia aplikacji a czasami wcale 
## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.0.8-play 2023.06.02 oraz testowane na 8229-dev-play
  - Wersja Androida: 13
  - Adres URL dziennika: vulcan.net.pl

**Comment by mklkj** [comment]
To nie jest błąd Wulkanowego. Dokładnie ten sam problem uświadczysz przy logowaniu przez stronę www dziennika, na co wielokrotnie sam trafiałem
