### ISSUE TITLE
Apka na wersji DEV 8441 crashuje po zmianie motywu z dowolnego na dowolny

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#2418]
## Co powinno się dziać
Apka nie powinna crashować podczas zmiany motywu

## Co się dzieje
Apka crashuje podczas zmiany motywu z komunikatem:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.wulkanowy.dev/io.github.wulkanowy.ui.modules.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.ContentFrameLayout.setDecorPadding(int, int, int, int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5917)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5808)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5876)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.ContentFrameLayout.setDecorPadding(int, int, int, int)' on a null object reference
	at androidx.appcompat.app.AppCompatDelegateImpl.applyFixedSizeWindow(AppCompatDelegateImpl.java:1109)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:903)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:763)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:203)
	at io.github.wulkanowy.ui.modules.main.MainActivity.onCreate(MainActivity.kt:114)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	... 17 more

```

## Jak to zrobić kolejny raz:
https://github.com/wulkanowy/wulkanowy/assets/43276401/393f2ad8-0eeb-49b4-b282-211398c3cf2e

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: DEV 8441 2024-02-08
  - Wersja Androida: 13 
  - Adres URL dziennika: Nie dotyczy

**Comment by mklkj** [comment]
Sprawdziłem na DEV 8441 na Redmi z Androidem 11 oraz na Pixelu z Androidem 14 i nie udało mi się tego odtworzyć. 

Czy to nie jest przypadkiem jakoś zmodyfikowany Android? Jeśli tak, to zamykam

**Comment by Zaptyp** [comment]
To nie jest żaden zmodyfikowany soft:
![Screenshot_2024-02-09-06-09-51-399_com.android.settings.jpg](https://github.com/wulkanowy/wulkanowy/assets/43276401/4e12d7fe-3133-4cf5-8478-78e7a6236fdb)

![Screenshot_2024-02-09-06-11-00-043_io.github.vvb2060.keyattestation.jpg](https://github.com/wulkanowy/wulkanowy/assets/43276401/66cb0007-2da1-4d7f-9137-9b8c34ef5685)

**Comment by tadekdudek** [comment]
Stockowy android ≠ niezmodyfikowany android, a miui jest jednym z najbardziej zmodyfikowanych wersji. U mnie na androidzie 13/LineageOS nic się nie crashuje.

**Comment by Zaptyp** [comment]
> Stockowy android ≠ niezmodyfikowany android, a miui jest jednym z najbardziej zmodyfikowanych wersji. U mnie na androidzie 13/LineageOS nic się nie crashuje.

Nie jest to możliwe że jest to problem MIUI bo na wersji release wszystko działa poprawnie a podejrzewam że crash występuje z powodu zmian które powstały na developie lub jego bibliotekach

**Comment by tadekdudek** [comment]
Ale nie zmienia to faktu, że problem (jak na razie) został zaobserwowany tylko na miui 14 i nigdzie więcej. Crash jest spowodowany zmianami w stosunku do wersji release, ponieważ te zmiany są widocznie niekompatybilne z miui.

**Comment by mklkj** [comment]
Coś rzeczywiście jest na rzeczy, ale to nie tyle ma związek ze zmianą motywu co z restartem aktywności, która następuje również przy przełączaniu użytkowników:

![obraz](https://github.com/wulkanowy/wulkanowy/assets/12243282/92226705-26ef-48e0-85a8-24942c1ab4f9)
