### ISSUE TITLE
Błąd po updacie na splashscreenie

### ISSUE THREAD

**Issue by doteq** [wulkanowy/wulkanowy#246]
## Co powinno się dziać?

Aplikacja się powinna uruchomić

## Co się dzieje

Aplikacja wywala toasta "Wystąpił nieoczekiwany błąd" i zostaje na splashscreenie

## Jak to zrobić kolejny raz

Zupdateować z wersji dev1726 do dev1752 

## Informacje o urządzeniu i dzienniku

Wersja aplikacji: DEV1752 (https://app.bitrise.io/artifact/11999290/p/ebf04dbbdac9170966c997d81da0f152)

Wersja Androida: 9

Adres URL dziennika: nie dotyczy

## Stacktrace
```
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:139) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:119) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:256) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at androidx.room.util.DBUtil.query(DBUtil.java:54) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.github.wulkanowy.data.db.dao.StudentDao_Impl$6.call(StudentDao_Impl.java:237) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.github.wulkanowy.data.db.dao.StudentDao_Impl$6.call(StudentDao_Impl.java:234) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Maybe.subscribe(Maybe.java:4262) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Maybe.subscribe(Maybe.java:4262) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.maybe.MaybeFilter.subscribeActual(MaybeFilter.java:39) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Maybe.subscribe(Maybe.java:4262) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.maybe.MaybeIsEmptySingle.subscribeActual(MaybeIsEmptySingle.java:49) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Single.subscribe(Single.java:3575) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Single.subscribe(Single.java:3575) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 02-15 01:10:08.542 5613 5613 E Wulkanowy: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by kapi2289** [comment]
Błąd wystąpił, ponieważ zainstalowałeś aplikację z niższą wersją bazy danych, wystarczy odinstalować i zainstalować ponownie.

**Comment by kapi2289** [comment]
Ale to i tak powinno być naprawione. Musimy stworzyć migracje cofające wersję bazy danych, aby było możliwe downgrade'owanie.

**Comment by doteq** [comment]
@kapi2289 Czytaj ze zrozumieniem; nie zdowngradowałem tylko zupdateowłem. Na discordzie pisaliśmy o powodzie.

**Comment by kapi2289** [comment]
1. Wyższy numer builda nie zawsze oznacza wyższą wersję, ponieważ bitrise buduje także PRy.
2. Między tymi wersjami zmieniła się nazwa tabeli lekcji zrealizowanych, więc ten błąd nie wystąpi w wersji produkcyjnej.
3. Wsparcie dla downgrade'ów przydałoby się tak czy siak.

**Comment by kapi2289** [comment]
Ten błąd jest już rozwiązany, takie błędy będą się często zdarzały w wersjach DEV, nie dotyczy on raczej downgrade'ów, do tego otworzę inny issue, na razie zamykam.
