### ISSUE TITLE
Błędy 404

### ISSUE THREAD

**Issue by tomaszk8266** [wulkanowy/wulkanowy#2528]
## Co powinno się dziać

Apka powinna normalnie działać

## Co się dzieje

Wyskakują dziwne błędy 404:

`io.github.wulkanowy.sdk.scrapper.exception.ScrapperException: HTTP Error 404
	at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorInterceptor.checkForError(ErrorInterceptor.kt:52)
	at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorInterceptor.intercept(ErrorInterceptor.kt:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)`

Przez przeglądarkę działa.

## Jak to zrobić kolejny raz:

  1. Spróbować zsynchronizować apkę
  2. Wyskakuje 404

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.5.5-fdroid; tak samo jest na najnowszym dev 8634
  - Wersja Androida: 14 (LineageOS 21)
  - Adres URL dziennika: https://uonetplus.vulcan.net.pl

**Comment by mklkj** [comment]
Wina VULCANa, zaczął wypluwać na stronie głównej kawałki htmla, które triggerowały nasz error handler. Poprawione w 2.5.8
